### ISSUE TITLE
MVP release checklist

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [xyflow/multiverse#11]
- [ ] Landing page
  - https://www.figma.com/file/vKFPM2tMA9rNFx28z86qlh/NodePacks-UI?type=design&node-id=33-2&mode=design&t=fANJoHywE6IzSRjx-0
  - Icon explainers of what multiverse is
    - No dependency hell: "This is NOT a component library. It's a collection of re-usable components that you can copy and paste into your apps."
    - ...?
  - Tease upcoming packs
    - Hand-drawn wireframes
    - Electrical engineering pack?
    - Workflow builder pack?
- [ ] Shapes pack
  - Go cannibalise the pro example 
- [ ] Set up gh discussions for pack proposals / discussion / voting (see https://github.com/orgs/supabase/discussions/5)
- [ ] Work out static flows maybe?
- [ ] Comment node describing what a pack is about
- [ ] Port music pack to svelte
- [ ] Style tweaks
- [ ] Work out view transitions from node -> node inspector/overview
- [ ] Shikijs highlighting theme
- [ ] Add copy & paste button
